/**
 * Tenant-scoped repositories (SDD-006 §Aislamiento por capas, point 1: "Repositorios con alcance").
 *
 * `createTenantDb(pool).forOrg(orgId)` is the *only* place an `org_id` is ever accepted as a raw
 * argument in this module's public surface; every method reachable from the object it returns closes
 * over that `orgId` and runs inside `withTenantTx(pool, orgId, ...)`, so RLS (not application code) is
 * what actually keeps one org's rows out of another's. A `projectId` that belongs to a different org
 * (or doesn't exist) simply isn't visible once `app.org_id` is set — `get()`/`findById` etc. resolve to
 * `null` exactly the same way for "wrong org" and "doesn't exist", which is deliberate: the HTTP layer
 * built on top of this maps both to a 404 (SDD-006 §Arquitectura: "Cualquier recurso de otra
 * organización o proyecto responde 404, nunca 403").
 */
import { and, desc, eq, inArray } from 'drizzle-orm';
import type { Pool } from 'pg';
import { assertNoSecretsInAuditMetadata } from './audit-metadata.js';
import { auditLog } from './schema/audit.js';
import { user } from './schema/auth.js';
import { projectMembers, projectRole, projects } from './schema/projects.js';
import { withTenantTx } from './tenant.js';
import { buildDocumentsRepository, type DocumentsRepository } from './documents-repository.js';

export type ProjectRecord = typeof projects.$inferSelect;
export type ProjectMemberRecord = typeof projectMembers.$inferSelect;
export type ProjectRole = (typeof projectRole.enumValues)[number];
export type AuditLogRecord = typeof auditLog.$inferSelect;

/** A `project_members` row joined with the member's `user` row (SDD-006 §Modelo de datos: `user` is a
 * global, no-RLS better-auth table, so this join is safe inside the same `withTenantTx` — RLS still
 * scopes `project_members` itself). */
export interface ProjectMemberWithUser {
  projectId: string;
  userId: string;
  orgId: string;
  role: ProjectRole;
  email: string;
  name: string;
}

export interface NewAuditLogEntryInput {
  projectId?: string;
  actorType: 'user' | 'token';
  actorId: string;
  action: string;
  target: string;
  /** Rejected up front by `assertNoSecretsInAuditMetadata` (SDD-006 §Modelo de datos). */
  metadata?: Record<string, unknown>;
  ip?: string;
  userAgent?: string;
}

export interface NewProjectInput {
  slug: string;
  name: string;
  /** Always generated by the server (`prj_<16 lowercase hex>`); never accepted from a client request. */
  graphProjectId: string;
  settings?: Record<string, unknown>;
}

export interface ProjectMemberInput {
  userId: string;
  role: ProjectRole;
}

export interface ProjectsRepository {
  list(): Promise<ProjectRecord[]>;
  /** Only the projects `userId` has a `project_members` row in (SDD-006 §Aislamiento entre proyectos:
   * "por defecto nada. Un miembro de la organización sin fila en project_members no ve el proyecto") —
   * callers with an inherited org admin/owner role should call {@link ProjectsRepository.list} instead. */
  listForUser(userId: string): Promise<ProjectRecord[]>;
  findById(id: string): Promise<ProjectRecord | null>;
  findBySlug(slug: string): Promise<ProjectRecord | null>;
  findByGraphProjectId(graphProjectId: string): Promise<ProjectRecord | null>;
  create(input: NewProjectInput): Promise<ProjectRecord>;
  /** Full replacement of the `settings` jsonb column (WO-107: the settings screen always submits the
   * complete, validated settings object back, never a partial patch). */
  updateSettings(id: string, settings: Record<string, unknown>): Promise<ProjectRecord>;
}

export interface MembersRepository {
  /** Every project membership a given user holds within this org (across all of its projects). */
  listForUser(userId: string): Promise<ProjectMemberRecord[]>;
}

export interface AuditLogRepository {
  /** Append-only (enforced at the database grant level too — `prdm_app` has no UPDATE/DELETE here). */
  record(entry: NewAuditLogEntryInput): Promise<AuditLogRecord>;
  list(): Promise<AuditLogRecord[]>;
}

export interface ProjectMembersRepository {
  list(): Promise<ProjectMemberWithUser[]>;
  /** `null` when `userId` has no `project_members` row for this project — the "an org member without a
   * row can't see the project" check (SDD-006 §Aislamiento entre proyectos) reads this directly. */
  findForUser(userId: string): Promise<ProjectMemberRecord | null>;
  upsert(input: ProjectMemberInput): Promise<ProjectMemberRecord>;
  remove(userId: string): Promise<void>;
}

export interface ProjectScope {
  /** `null` for a wrong-org or nonexistent id alike — see the module doc comment. */
  get(): Promise<ProjectRecord | null>;
  members: ProjectMembersRepository;
  documents: DocumentsRepository;
}

export interface OrgRepositories {
  projects: ProjectsRepository;
  members: MembersRepository;
  auditLog: AuditLogRepository;
  forProject(projectId: string): ProjectScope;
}

export interface TenantDb {
  forOrg(orgId: string): OrgRepositories;
}

export function createTenantDb(pool: Pool): TenantDb {
  return {
    forOrg(orgId: string): OrgRepositories {
      return {
        projects: buildProjectsRepository(pool, orgId),
        members: buildMembersRepository(pool, orgId),
        auditLog: buildAuditLogRepository(pool, orgId),
        forProject: (projectId: string) => buildProjectScope(pool, orgId, projectId),
      };
    },
  };
}

function buildProjectsRepository(pool: Pool, orgId: string): ProjectsRepository {
  return {
    list: () => withTenantTx(pool, orgId, (tx) => tx.select().from(projects)),
    listForUser: (userId) =>
      withTenantTx(pool, orgId, async (tx) => {
        const memberships = await tx.select({ projectId: projectMembers.projectId }).from(projectMembers).where(eq(projectMembers.userId, userId));
        if (memberships.length === 0) return [];
        const projectIds = memberships.map((m) => m.projectId);
        return tx.select().from(projects).where(inArray(projects.id, projectIds));
      }),
    findById: (id) =>
      withTenantTx(pool, orgId, async (tx) => (await tx.select().from(projects).where(eq(projects.id, id)))[0] ?? null),
    findBySlug: (slug) =>
      withTenantTx(pool, orgId, async (tx) => (await tx.select().from(projects).where(eq(projects.slug, slug)))[0] ?? null),
    findByGraphProjectId: (graphProjectId) =>
      withTenantTx(
        pool,
        orgId,
        async (tx) => (await tx.select().from(projects).where(eq(projects.graphProjectId, graphProjectId)))[0] ?? null,
      ),
    create: (input) =>
      withTenantTx(pool, orgId, async (tx) => {
        const [row] = await tx
          .insert(projects)
          .values({ orgId, slug: input.slug, name: input.name, graphProjectId: input.graphProjectId, settings: input.settings ?? {} })
          .returning();
        return row!;
      }),
    updateSettings: (id, settings) =>
      withTenantTx(pool, orgId, async (tx) => {
        const [row] = await tx.update(projects).set({ settings }).where(eq(projects.id, id)).returning();
        if (!row) throw new Error(`project ${id} not found while updating settings`);
        return row;
      }),
  };
}

function buildMembersRepository(pool: Pool, orgId: string): MembersRepository {
  return {
    listForUser: (userId) =>
      withTenantTx(pool, orgId, (tx) => tx.select().from(projectMembers).where(eq(projectMembers.userId, userId))),
  };
}

function buildAuditLogRepository(pool: Pool, orgId: string): AuditLogRepository {
  return {
    // `async` (rather than a plain arrow returning `withTenantTx(...)`) matters here: it turns the
    // synchronous throw from `assertNoSecretsInAuditMetadata` into a rejected promise instead of an
    // exception thrown at call time, so `record(...)` is always safe to treat as a promise.
    record: async (entry) => {
      assertNoSecretsInAuditMetadata(entry.metadata ?? {});
      return withTenantTx(pool, orgId, async (tx) => {
        const [row] = await tx
          .insert(auditLog)
          .values({
            orgId,
            projectId: entry.projectId,
            actorType: entry.actorType,
            actorId: entry.actorId,
            action: entry.action,
            target: entry.target,
            metadata: entry.metadata ?? {},
            ip: entry.ip,
            userAgent: entry.userAgent,
          })
          .returning();
        return row!;
      });
    },
    list: () => withTenantTx(pool, orgId, (tx) => tx.select().from(auditLog).orderBy(desc(auditLog.createdAt))),
  };
}

function buildProjectScope(pool: Pool, orgId: string, projectId: string): ProjectScope {
  return {
    get: () =>
      withTenantTx(pool, orgId, async (tx) => (await tx.select().from(projects).where(eq(projects.id, projectId)))[0] ?? null),
    documents: buildDocumentsRepository(pool, orgId, projectId),
    members: {
      list: () =>
        withTenantTx(pool, orgId, (tx) =>
          tx
            .select({ projectId: projectMembers.projectId, userId: projectMembers.userId, orgId: projectMembers.orgId, role: projectMembers.role, email: user.email, name: user.name })
            .from(projectMembers)
            .innerJoin(user, eq(user.id, projectMembers.userId))
            .where(eq(projectMembers.projectId, projectId)),
        ),
      findForUser: (userId) =>
        withTenantTx(
          pool,
          orgId,
          async (tx) =>
            (await tx.select().from(projectMembers).where(and(eq(projectMembers.projectId, projectId), eq(projectMembers.userId, userId))))[0] ?? null,
        ),
      upsert: (input) =>
        withTenantTx(pool, orgId, async (tx) => {
          const [row] = await tx
            .insert(projectMembers)
            .values({ projectId, orgId, userId: input.userId, role: input.role })
            .onConflictDoUpdate({ target: [projectMembers.projectId, projectMembers.userId], set: { role: input.role } })
            .returning();
          return row!;
        }),
      remove: (userId) =>
        withTenantTx(pool, orgId, async (tx) => {
          await tx.delete(projectMembers).where(and(eq(projectMembers.projectId, projectId), eq(projectMembers.userId, userId)));
        }),
    },
  };
}
