/**
 * Tenant-scoped repositories (SDD-006 §Aislamiento por capas, point 1: "Repositorios con alcance").
 *
 * `createTenantDb(pool).forOrg(orgId)` is the *only* place an `org_id` is ever accepted as a raw
 * argument in this module's public surface; every method reachable from the object it returns closes
 * over that `orgId` and runs inside `withTenantTx(pool, orgId, ...)`, so RLS (not application code) is
 * what actually keeps one org's rows out of another's. A `projectId` that belongs to a different org
 * (or doesn't exist) simply isn't visible once `app.org_id` is set — `get()`/`findById` etc. resolve to
 * `null` exactly the same way for "wrong org" and "doesn't exist", which is deliberate: the HTTP layer
 * built on top of this maps both to a 404 (SDD-006 §Arquitectura: "Cualquier recurso de otra
 * organización o proyecto responde 404, nunca 403").
 */
import { and, eq } from 'drizzle-orm';
import type { Pool } from 'pg';
import { projectMembers, projectRole, projects } from './schema/projects.js';
import { withTenantTx } from './tenant.js';

export type ProjectRecord = typeof projects.$inferSelect;
export type ProjectMemberRecord = typeof projectMembers.$inferSelect;
export type ProjectRole = (typeof projectRole.enumValues)[number];

export interface NewProjectInput {
  slug: string;
  name: string;
  /** Always generated by the server (`prj_<16 lowercase hex>`); never accepted from a client request. */
  graphProjectId: string;
  settings?: Record<string, unknown>;
}

export interface ProjectMemberInput {
  userId: string;
  role: ProjectRole;
}

export interface ProjectsRepository {
  list(): Promise<ProjectRecord[]>;
  findById(id: string): Promise<ProjectRecord | null>;
  findBySlug(slug: string): Promise<ProjectRecord | null>;
  findByGraphProjectId(graphProjectId: string): Promise<ProjectRecord | null>;
  create(input: NewProjectInput): Promise<ProjectRecord>;
}

export interface MembersRepository {
  /** Every project membership a given user holds within this org (across all of its projects). */
  listForUser(userId: string): Promise<ProjectMemberRecord[]>;
}

export interface ProjectMembersRepository {
  list(): Promise<ProjectMemberRecord[]>;
  upsert(input: ProjectMemberInput): Promise<ProjectMemberRecord>;
  remove(userId: string): Promise<void>;
}

export interface ProjectScope {
  /** `null` for a wrong-org or nonexistent id alike — see the module doc comment. */
  get(): Promise<ProjectRecord | null>;
  members: ProjectMembersRepository;
}

export interface OrgRepositories {
  projects: ProjectsRepository;
  members: MembersRepository;
  forProject(projectId: string): ProjectScope;
}

export interface TenantDb {
  forOrg(orgId: string): OrgRepositories;
}

export function createTenantDb(pool: Pool): TenantDb {
  return {
    forOrg(orgId: string): OrgRepositories {
      return {
        projects: buildProjectsRepository(pool, orgId),
        members: buildMembersRepository(pool, orgId),
        forProject: (projectId: string) => buildProjectScope(pool, orgId, projectId),
      };
    },
  };
}

function buildProjectsRepository(pool: Pool, orgId: string): ProjectsRepository {
  return {
    list: () => withTenantTx(pool, orgId, (tx) => tx.select().from(projects)),
    findById: (id) =>
      withTenantTx(pool, orgId, async (tx) => (await tx.select().from(projects).where(eq(projects.id, id)))[0] ?? null),
    findBySlug: (slug) =>
      withTenantTx(pool, orgId, async (tx) => (await tx.select().from(projects).where(eq(projects.slug, slug)))[0] ?? null),
    findByGraphProjectId: (graphProjectId) =>
      withTenantTx(
        pool,
        orgId,
        async (tx) => (await tx.select().from(projects).where(eq(projects.graphProjectId, graphProjectId)))[0] ?? null,
      ),
    create: (input) =>
      withTenantTx(pool, orgId, async (tx) => {
        const [row] = await tx
          .insert(projects)
          .values({ orgId, slug: input.slug, name: input.name, graphProjectId: input.graphProjectId, settings: input.settings ?? {} })
          .returning();
        return row!;
      }),
  };
}

function buildMembersRepository(pool: Pool, orgId: string): MembersRepository {
  return {
    listForUser: (userId) =>
      withTenantTx(pool, orgId, (tx) => tx.select().from(projectMembers).where(eq(projectMembers.userId, userId))),
  };
}

function buildProjectScope(pool: Pool, orgId: string, projectId: string): ProjectScope {
  return {
    get: () =>
      withTenantTx(pool, orgId, async (tx) => (await tx.select().from(projects).where(eq(projects.id, projectId)))[0] ?? null),
    members: {
      list: () =>
        withTenantTx(pool, orgId, (tx) => tx.select().from(projectMembers).where(eq(projectMembers.projectId, projectId))),
      upsert: (input) =>
        withTenantTx(pool, orgId, async (tx) => {
          const [row] = await tx
            .insert(projectMembers)
            .values({ projectId, orgId, userId: input.userId, role: input.role })
            .onConflictDoUpdate({ target: [projectMembers.projectId, projectMembers.userId], set: { role: input.role } })
            .returning();
          return row!;
        }),
      remove: (userId) =>
        withTenantTx(pool, orgId, async (tx) => {
          await tx.delete(projectMembers).where(and(eq(projectMembers.projectId, projectId), eq(projectMembers.userId, userId)));
        }),
    },
  };
}
