// Generated by scripts/validate-graph-model.mjs from docs/model/graph-model.json (x-prdm.constraints/x-prdm.indexes).
// This is the authoritative DDL for the schema (mirrors packages/core/src/graph/migrations.ts exactly);
// it is NOT the output of mcp-neo4j-data-modeling get_constraints_cypher_queries, which cannot express
// this schema's composite (project_id, <key>) uniqueness constraints (see x-prdm.compositeKeyLimitation).
// Schema version: 2 (migrations: 1:initial_schema, 2:multi_project)

// -- Constraints ---------------------------------------------------------------------------

CREATE CONSTRAINT schema_migration_version IF NOT EXISTS FOR (n:SchemaMigration) REQUIRE n.version IS UNIQUE;
CREATE CONSTRAINT project_id IF NOT EXISTS FOR (n:Project) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT node_project_id IF NOT EXISTS FOR (n:Node) REQUIRE (n.project_id, n.id) IS UNIQUE;
CREATE CONSTRAINT coderef_project_key IF NOT EXISTS FOR (n:CodeRef) REQUIRE (n.project_id, n.key) IS UNIQUE;
CREATE CONSTRAINT commit_project_sha IF NOT EXISTS FOR (n:Commit) REQUIRE (n.project_id, n.sha) IS UNIQUE;
CREATE CONSTRAINT actor_project_id IF NOT EXISTS FOR (n:Actor) REQUIRE (n.project_id, n.id) IS UNIQUE;

// -- Indexes --------------------------------------------------------------------------------

CREATE INDEX node_project_id_idx IF NOT EXISTS FOR (n:Node) ON (n.project_id);
CREATE INDEX coderef_project_id_idx IF NOT EXISTS FOR (n:CodeRef) ON (n.project_id);
CREATE INDEX commit_project_id_idx IF NOT EXISTS FOR (n:Commit) ON (n.project_id);
CREATE INDEX actor_project_id_idx IF NOT EXISTS FOR (n:Actor) ON (n.project_id);
CREATE INDEX node_project_status IF NOT EXISTS FOR (n:Node) ON (n.project_id, n.status);
CREATE FULLTEXT INDEX node_text_v2 IF NOT EXISTS FOR (n:Node) ON EACH [n.title, n.body, n.tags_text, n.project_id]; // analyzer: standard-no-stop-words (Not set explicitly by CREATE FULLTEXT INDEX in migrations.ts (no OPTIONS clause) -- this is Neo4j 2026.08.1's default fulltext analyzer, empirically confirmed via SHOW INDEXES in graph-model.test.ts. ADR-002 D5 documents 'standard-no-stop-words' as if configured; it is actually inherited from the server default. See x-prdm.discrepancies.)
