/**
 * `projects` and `project_members` (SDD-006 §Modelo de datos / §Aislamiento por capas).
 *
 * Both tables get `org_id NOT NULL`, RLS **enabled and forced** (so even the table owner is subject
 * to it unless it bypasses RLS outright — `prdm_owner` is the bootstrap superuser and always bypasses
 * RLS regardless of FORCE, which is exactly why test fixtures insert through `pg.ownerPool`), and the
 * exact policy shape from the SDD: `USING/WITH CHECK (org_id = NULLIF(current_setting('app.org_id',
 * true), ''))`. `NULLIF(..., '')` turns an *unset* `app.org_id` (which `current_setting(name, true)`
 * — the "missing OK" form — returns as `''`, not `NULL`) into a real `NULL`, so the comparison itself
 * (rather than a separate `IS NULL` branch) already yields no rows when no tenant has been selected.
 *
 * `project_members.(project_id, org_id)` is a composite foreign key into `projects(id, org_id)` (not
 * just `projects(id)`), so a row can never claim a `project_id` that actually belongs to a different
 * org's project — the exact mechanism SDD-006 relies on for "a cross-org reference fails at the FK",
 * which is why `projects` also carries `UNIQUE (id, org_id)` (a composite FK's target must be unique).
 */
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { organization, user } from './auth.js';

export const projectRole = pgEnum('project_role', ['admin', 'editor', 'developer', 'commenter', 'viewer']);

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orgId: text('org_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    /** Always generated by the server (`prj_<16 lowercase hex>`), never client-supplied. */
    graphProjectId: text('graph_project_id').notNull().unique(),
    settings: jsonb('settings').notNull().default({}),
    graphVersion: bigint('graph_version', { mode: 'bigint' })
      .notNull()
      .default(sql`0`),
    graphDirty: boolean('graph_dirty').notNull().default(false),
    archivedAt: timestamp('archived_at', { withTimezone: true, mode: 'date' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (table) => [
    unique('projects_org_id_slug_key').on(table.orgId, table.slug),
    // Target of project_members' composite FK below.
    unique('projects_id_org_id_key').on(table.id, table.orgId),
    index('projects_org_id_idx').on(table.orgId),
    check('projects_graph_project_id_format', sql`${table.graphProjectId} ~ '^prj_[0-9a-f]{16}$'`),
  ],
);

export const projectMembers = pgTable(
  'project_members',
  {
    projectId: uuid('project_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    orgId: text('org_id').notNull(),
    role: projectRole('role').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.projectId, table.userId], name: 'project_members_pkey' }),
    foreignKey({
      columns: [table.projectId, table.orgId],
      foreignColumns: [projects.id, projects.orgId],
      name: 'project_members_project_org_fk',
    }),
    index('project_members_org_id_idx').on(table.orgId),
  ],
);
